const BASE_URL = "http://swapi.dev/api/";
const IMAGES = {
    "Luke Skywalker": "img/characters/lukeskywalker.png",
    "C-3PO": "img/characters/c-3po.png",
    "R2-D2": 'img/characters/r2-d2.png',
    "Obi-Wan Kenobi": "img/characters/obi-wan-kenobi.png",
    "Anakin Skywalker": "img/characters/anakin-skywalker.png",
    "Padmé Amidala": "img/characters/padme-amidala.png",
    "Barriss Offee": "img/characters/barriss-offee.jpeg",
    "Ayla Secura": "img/characters/ayla-secura.jpeg",
    "Jabba Desilijic Tiure": "img/characters/jabba-desilijic-tiure.png",
    "Darth Vader": "img/characters/darth-vader.png",
    "Yoda": "img/characters/yoda.png",
    "Boba Fett": "img/characters/boba-fett.png",
    "Palpatine": "img/characters/palpatine.png",
    "Shmi Skywalker": "img/characters/shmi-skywalker.png",
    "Ki-Adi-Mundi": "img/characters/ki-adi-mundi.png",
    "Jar Jar Binks": "img/characters/jar-jar-binks.png",
    "Nute Gunray": "img/characters/nute-gunray.png",
    "Watto": "img/characters/watto.png",
    "Poggle the Lesser": "img/characters/poggle-the-lesser.png",
    "Mace Windu": "img/characters/mace-windu.png",
    "Cliegg Lars": "img/characters/cliegglars.png",
    "Kit Fisto": "img/characters/kitfisto.png",
    "Lama Su": "img/characters/lama-su.jpeg",
    "Dexter Jettster": "img/characters/dexter-jettster.png",
    "Luminara Unduli": "img/characters/luminara-unduli.jpeg",
    "Taun We": "img/characters/taun-we.png",
    "Jocasta Nu": "img/characters/jocasta-nu.png",
    "Beru Whitesun lars": "img/characters/BeruCardTrader.png",
    "Mas Amedda": "img/characters/mas-amedda.png",
    "Plo Koon": "img/characters/plo_koon.png",
    "San Hill": "img/characters/san-hill.png",
    "Wat Tambor": "img/characters/wat-tambor.png",
    "R4-P17": "img/characters/R4-P17.png",
    "R5-D4": "img/characters/r5-d4.jpeg",
    "Zam Wesell": "img/characters/zam-wesell.jpeg",
    "Leia Organa": "img/characters/leia-organa.png",
    "Wilhuff Tarkin": "img/characters/wilhuffTarkin.jpeg",
    "Greedo": "img/characters/greedo.jpeg",
    "Biggs Darklighter": "img/characters/biggsDarklighter.jpeg",
    "Jek Tono Porkins": "img/characters/jekTonoPorkins.png",
    "Han Solo": "img/characters/hanSolo.png",
    "Chewbacca": "img/characters/chewbacca.png",
    "Wedge Antilles": "img/characters/wedgeAntilles.jpeg",
    "Raymus Antilles": "img/characters/raymusAntilles.jpeg",
    "Owen Lars": "img/characters/OwenLars.jpeg",
    "IG-88": "img/characters/IG-88.jpeg",
    "Bossk": "img/characters/bossk.jpeg",
    "Lobot": "img/characters/Lobot_SWDR.png",
    "Lando Calrissian": "img/characters/landoCalrissian.jpeg",
    "Ackbar": "img/characters/ackbar.png",
    "Wicket Systri Warrick": "img/characters/wicket-systri-warrick.jpeg",
    "Arvel Crynyd": "img/characters/arvel-crynyd.jpeg",
    "Mon Mothma": "img/characters/monMothma.jpeg",
    "Nien Nunb": "img/characters/nienNunb.png",
    "Bib Fortuna": "img/characters/bibFortuna.jpeg",
    "Qui-Gon Jinn": "img/characters/qui-GonJinn.png",
    "Roos Tarpals": "img/characters/roosTarpals.jpeg",
    "Finis Valorum": "img/characters/finisValorum.jpeg",
    "Rugor Nass": "img/characters/rugorNass.png",
    "Sebulba": "img/characters/sebulba.jpeg",
    "Ric Olié": "img/characters/ric-olie.jpeg",
    "Ben Quadinaros": "img/characters/BenQuadinaros.jpeg",
    "Quarsh Panaka": "img/characters/QuarshPanaka.png",
    "Dud Bolt": "img/characters/DudBolt.png",
    "Ratts Tyerel": "img/characters/RattsHS.jpeg",
    "Darth Maul": "img/characters/DarthMaul.png",
    "Gasgano": "img/characters/Gasgano.jpeg",
    "Adi Gallia": "img/characters/AdiGallia.png",
    "Saesee Tiin": "img/characters/SaeseeTiin.jpeg",
    "Eeth Koth": "img/characters/Eeth_Koth.jpeg",
    "Yarael Poof": "img/characters/YaraelPoof.jpeg",
    "Plo Koon": "img/characters/plo_koon.png",
    "Gregar Typho": "img/characters/GregarTypho.png",
    "Bail Prestor Organa": "img/characters/BailPrestorOrgana.jpg",
    "Dormé": "img/characters/Dorme.jpeg",
    "Jango Fett": "img/characters/JangoFett.jpeg",
    "Dooku": "img/characters/Dooku.png",
    "Cordé": "img/characters/Cord.jpeg",
    "Sly Moore": "img/characters/sly-moore.jpeg",
    "Shaak Ti": "img/characters/ShaakTi.jpeg",
    "Tion Medon": "img/characters/TionMedon.jpeg",
    "Tarfful": "img/characters/Tarfful.jpeg",
    "Grievous": "img/characters/Grievous.jpeg"
};
const TITLES = {
    "name": "Name",
    "birth_year": "Date of birth",
    "gender": "Gender",
    "imgSrc": "Avatar"
}
const WOOKIEE_KEYS = {
    "next": "whwokao",
    "previous": "akrcwohoahoohuc",
    "results": "rcwochuanaoc",
    "name": "whrascwo"
}